#!/bin/sh

set -e

. /usr/share/debconf/confmodule

if [ -f /usr/share/dbconfig-common/dpkg/config ]; then
  dbc_dbtypes="mysql"
  dbc_dbname="sirocco"
  dbc_dbuser="sirocco"
  dbc_authmethod_user="password"
  . /usr/share/dbconfig-common/dpkg/config
  dbc_go sirocco-server $@
fi
