#!/bin/sh

set -e

if [ "${1}" = "purge" ] ; then

  if [ -f /usr/share/debconf/confmodule ]; then
    . /usr/share/debconf/confmodule
  fi
  if [ -f /usr/share/dbconfig-common/dpkg/postrm ]; then
    . /usr/share/dbconfig-common/dpkg/postrm
    dbc_go sirocco-server $@
  fi

fi
