#!/bin/sh

set -e

if [ "${1}" = "remove" ] && [ -r /usr/share/debconf/confmodule ] && [ -r /usr/share/dbconfig-common/dpkg/prerm ] ; then
  . /usr/share/debconf/confmodule
  . /usr/share/dbconfig-common/dpkg/prerm
  dbc_go sirocco-server $@

  asadmin stop-domain sirocco
  asadmin delete-domain sirocco

  if [ -d /usr/share/glassfish/lib/endorsed ]; then
    for f in $(ls /usr/share/sirocco-server/lib/endorsed); do
      rm /usr/share/glassfish/lib/endorsed/$f
    done
  fi

fi

#DEBHELPER#

